language: generic
sudo: require
matrix:
  include:
  - os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex draft.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases

  api_key:
    secure: MIIJKwIBAAKCAgEAzUfxDeuAiPTft/YZdIPD6hGSjGHwynTiFkDxT0KC+KrS4skN
nK8+OIj6iae4EKE8XzWqcUnBYOrk9DkNAm79sD1LVi00bgME1G4v2YZs8rpR/e91
YeyIwvAmcK5lGjuOGVZJt8vAwVk4vdpicp5ndXNfyMdHaruEwYerwngDJhyKP5xS
TruhCfQUB7lOmwdnivjVait/3RNkmWg5oOFITiMieRAscn6w0OPlxS2TJmRH8gvO
YP25CbZV8AZ7ZNMtAz24jSl2SQFkg9UUSxTsI8lztZvJlT0ibXYTNaOMg19mKD2E
Dh2gvbKdT0giSt9A0+jjDRnuehDeU7FnsGukkU+WktXnFOmTZzxkgYA4TY3g8diG
2i1jqa6HJJLnlY37p097QWl54osfSynk6jMMtwym+TkUgQ6QjCKdRebzW8epQMZ1
4+uqEoTtV+g/JV5sRj1p8kr5G5i0UNupQn36rBpraMRLAdTnIfb2XOrOuoVUzUyP
3lE8rLe8w7uqG5EJfbHSS8j2mv+6LZsiXohxh4u/tYTqdklFqiaNncBL1m7yI8J2
au1FHGHk5KzUfiZ1rXwdhBDpP0mkNkVqqdD6NvoHViukBfwfmal1IA7Rb9y/NhSv
wWYmuKEpE5NlcsN5M0lo1ecKnFYohqKJQTHqgNxAgM73LBvPkVza3aVxK6ECAwEA
AQKCAgEAsGOFzNk0K/qFlXPgsY5bNHB/BSNPHRfMASUydFGJapSV+oqZqK2oADor
VUcJUTjKQGFDoG6ovFd5/iRbemDWma5BYr4bFACCEOrRMM9iJDtXIqS0rzzo0uA5
l48yjpTn5/uOAmEQstKwf+n7t9NGwNQvVL1vL1YLn6OtQb+PrRrO7BOtYbu1h3D0
GSLwWSPGo9JmxwCzsMnuIic9hXCuiX2FLJNqLcOQuR1qHMCpdU6rx16/qfW6Ho9P
TpyzQJJ4VhWd06Xx3o9UyDa6Zj2HHsUGKOHBF/xc7cOMhAWRQn0hsagSJXLt4LJu
m2Y3GTC2ap/tIR/MG5UNBMsmdqA32Z57oOj2dP431du5MsXi/zR3uIH09d+cBGOq
N1z+PcngHBOEy6QmWmgAz9zyAeerfRhOO8Eu5kXeB7D3hMcSlxROtCTrsuXTgkdz
WFX495PwY/E1T57gin3qfo28kSf6mS82bJ6tS0gS2Mp/UYoegGATuwC30iWA1aPH
Nh/BbUhOk9feQtkajkXkzJ2AWTT4yxDoR0uCFiNVhtZY8RYvVo0aiNA18BQtHxF2
/Ri0PbSU/zjzya7L2SjR+znXPJvRXK/GRnQ+xFtjxc4s4/f6cXCelH8ZIPLZue7K
WHCtg8oQmvtfMdA3cYNj4qKpaTZj5iGKisEO/FYVr9jbo/eD4rECggEBAOsuROwT
8Fxb37kCc4TjXNM3AfOVyHBUTAVuCGhh/N3ZJbwsHl0TQdZjIRPBpEcnz1O7eHRn
5vZn8rbxBd1vhVlTXIcJcLm8Gj34KGABAWcDlqyRQbH+mWTdTTCHPFao4gZ6eeTd
TLPAwJp1RMbgfi+TvKbVoRR1e/oyepOpLcNKal7RkUICPvNofViFm9AYDfK8bEVi
dDs5vYGXRGqd4EP6k5vW4++l+T28YwT44/tfMIvizxbxyiLgPBfA3lBAQh7uJz8Q
8QVIyNsR9eA36AEP4YrMEd5N7qHEWT4//TqalYm2tEhGYc0+aGsnu9ofcAt8rGSg
Ea7CcLyQQS1lVb0CggEBAN90E6Yehmt4+4sURRxntwm9/oZdOXMwDT9YiArNMVRG
Ggl3HlD38XuLi5qvyWck4Ljvxqb+raEybN11ccpo9yUF2QemNBSL+treZukNqxe+
snDSuMCVLkIXe9076gLhNNnivb5UUXX8tk1aFbFOnRSrFtZGdjhlU9wy/4LKKIad
jpeR6ogOsDqxVZ7L9EUwkwQPmbIMXx1RdHm4uJ0345c+Zkh/JjSXWCLVx63vL0Kn
4Avgz6Gy3hM3jhfQH/s0lBkGQKyIpDjjPTFQjqij6pxtS1IdsVJmmBImKhwqrizo
B+KEfQsWgPU9ZFO9IgEU+h/SXK36I88Dat6HXpsiEbUCggEBALrABhjVCHO+vNvD
14l5pfdO4ezUTtLsDWXuZxzEWrCrwyw2eHH+XbRpCRYQGWwrb5YU8uS0sRGPn4un
vrmE2gYBjSLp2yqR9OCqkx0RD1UG43nq6pj2DEas+KOFb+N8vebZELwtAsBmWksM
ve2SzIDpNs/gKcX+ONGHjhB9Mgq2p9rdXRRmhihxG7/UcNMAluretrcuJA/3nMUw
IjLrZO92JgqEzIE7cbyVQKftH9Q3VWxvUXTt0U56cx2FmMNvE1JOWLnasRk6H8zd
6ToACun0+2tk+vdlOQ4ZxagJ1gLYR9CQVX5i7Ty2xuH4LlJZznZArQBGn2P/oNgL
UMZEhp0CggEBAJErZ0yIDkoqKjmb7J5cnyScI4yFajp0YFbkHFXwIvkeJfI6Sh7O
Rjs+WG8hfxYcdkaPuB5r3L+Z8/IYR9n5QX7zAqGej709h7bDwFXuRFZD1MfJjq/G
+2uCuDztnMVMLDrVvPG288lUaddtDCTJ7vEricWht1JCOi4Xj7oXviZem/HKoXTN
Hh6zcO2ekU6WFR0RSYfL08tHTQV7Ra0WTyzGJEs7F8YZAPB4tKZCexCx4bO11Q63
FuGjORQtaWmZKhHr5v5wM0imEO5F6LiU7Wm8868gjT/8WRWJZ9guvkN8Zwr5igc3
EobA4LoqaLoNN8aOsxlwJe1qyfZSOdtNUfUCggEBAJ7IbvyANpuAXsDVp7f8w2DG
g+tDN9JCoRX4XMBSTvPkP+ZHH5P42R3dm6QtOj/KiP1WXYz1K6R3HqSRk2jI9mnR
cZdEWVDvt56+hoLvkoAXU0XZUqx+n/KO+InWx6BpMxhx7tpYg2rqQEomZ7JZHCd2
Zgm1yJ4MFlcxpOdovgZ7Co9x2LAIUjv6Rvpm6zwomNEJIG4SK7A6e/A49CyW9KXX
xvHgW0ZRVFwXcQ9LCYLWHNddDnpwdDZNbhhDAjJFcYaCs5e8y8euqTAgHx7kDxax
PByai8rgWQezaCMuh2ibN/sEQjajf6o1c0wHSctLlP3VU+/GgVXfQgu2E/l0voE=
  file: tex/draft.pdf
  on:
    repo: CRIStAL-Sigma/test_deploy_travis
    tags: true
