language: generic
sudo: require
matrix:
  include:
  - os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex draft.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  api-key:
    secure: GbPcfLGUgF4hSLwzyCfxCDkYnuKwqqJ7K4/RWoPj2QnyV/0UPF9Pob+cQZ5jWAC4sYOYtOXcbpUO/KyGwf56+sVReoOwNUd5bcmzdv0hZf0LPapXcO6bTUDjse7ykv7Udrrunltt8+HCTEHxcp/e7xke0JCd/q6XFLGz7LkLWoXCuEmxJg6dGbrsrH46IiOctPGssIiwz7VX83Zets6BEAyjPMoQFpzNUgVFgsyaYXMcW0q0bNy1YlY0ku7CsD1GCN1Jy2IlV43q20lEhaVi4qnE+TvpSgahuiPr7AQTdfS/lnA2CLWth7t5fhAbqVKXtYMrhkM3FWGDAtSlR4oSVDAZbLZf4Eys6cjYdCLjil1vGVbmJzjbbCAJNMnqx6cKETINbA5uojU8Lg8lZM+LXo1lqWvtRI3wp9CgSwSyXy2yBhZJ66RBelCnCp87WPtbtfLFs9YRqAQ63itSv9B3ifhRH7qurwuGM9T9xhFbbrX5sDIsb6Sgj+X7I9/D15pUlHyGwKmR36t+0ga+A6aiB5U6wwybkEc7ppPxjB/SM2tv4YZTH1yR4oWBp67XqF4vsit1wtUCEvBNrJkMdgxMk00/zqaIZshFiWmVvtn5Mn/L1nbTa9Qn0q5ROiv9FxWqkJSIx60Lxe8DjmN4vnglejjEG8USbtLDnzYJe3ZiLug=
  file: tex/draft.pdf
  on:
    repo: CRIStAL-Sigma/test_deploy_travis
    tags: true
