language: generic
sudo: require
matrix:
  include:
  - os: linux
install:
- ". ./scripts/ensure_latex.sh"
- "./scripts/ensure_book_dependencies.sh"
script:
- cd tex
- pdflatex draft.tex
- cd ..
deploy:
  skip_cleanup: true
  provider: releases
  api-key:
    secure: ZM+iBgKnmEnzQfnYRN9uac6lzRpTd7WN8mlGTQ8J4ps2vNCFMoAkRWV3XKsTcuwBG5X04g2p5vXPKh6l/XnoNwXTMgfZ7EZ7KzRaG4HRqErHwFj32ujo6bZxqaCNhE00fsvjkWMiy8P7nuIh0Nf2hGwVE5PYhLl/hYmP43m/OECnC0mRRmD3BZngOOydnKHi4B/il80eNnLiA19SGmc+vKGiJHkTEnm8ofnbLlATg1oFDcVSQmQVPLemn6OfywPvTHrTTb41bvl4hLq8+g5TGUSyb0FS6510llVbsVJPo1mBzwAB5mKUFgH2OI9bsF+TfV8bKi4b5Wv3RAbCnpRwe2TL0ip2tZCPAkSIaXqatWWUk43PFhKI+4onBqxlehElUOUX27KLJGPj87igVbAfrgPysXu9PStp09nuvkoKTKB1NxDuKqOk/8garCOIGLy2Cgfd5HxbRMnXzHoRuk+0xCzYivquIKWHcl/7fUa39+ltHSVa9qexuuztiMFJreABRJrvJexuvwKRZWn3YVmVQ04MUUHPaTXH4dZ+HWAycNXu4mV79+LkXfR3qfFlAhX1mVvF0EvJN2fwxrxJckdXTsb2PEgT1KlH48uVmE1L5ngjdHdmj1J8fasxMkPSV236+SJ77qkUVVpSi2LROYoTNUpDzDPLekgvBr4BMHFUSIY=
  file: tex/draft.pdf
  on:
    repo: CRIStAL-Sigma/test_deploy_travis
    tags: true
